### ISSUE TITLE
【适配问题】请问任何AR眼镜都可以使用吗？

### ISSUE THREAD

**Issue by Paper-blue** [DiscreteTom/HyperStudio#1]
在纠结ar眼镜的生态问题，但是看到您的项目，很是心动，想问下任何AR眼镜都可以使用吗？

**Comment by DiscreteTom** [comment]
因为是使用了雷鸟AR的SDK实现的3dof定位，所以目前仅支持雷鸟AR (air + 1s)。不过如果其他AR眼镜提供PC端SDK的话也比较好接入
